-- this db holds the corp_gov tables, but imputed versions
create database corp_gov_imputed_scaled;

create table corp_gov_imputed_scaled.spx (
    `Tax` double DEFAULT NULL,
    `Norm NI to NI for Cmn %` double DEFAULT NULL,
    `Interest` double DEFAULT NULL,
    `OPM T12M` double DEFAULT NULL,
    `Asset` double DEFAULT NULL,
    `Fincl  l` double DEFAULT NULL,
    `Oper ROE` double DEFAULT NULL,
    `5Yr Avg Adj ROE` double DEFAULT NULL,
    `Dvd P/O` double DEFAULT NULL,
    `Sust Gr Rt` double DEFAULT NULL,
    `EBITDA/Sh` double DEFAULT NULL,
    `P/E` double DEFAULT NULL,
    `EPS` double DEFAULT NULL,
    `P/B` double DEFAULT NULL,
    `P/EBITDA` double DEFAULT NULL,
    `ROE` double DEFAULT NULL,
    `ROC` double DEFAULT NULL,
    `EV/EBITDA T12M` double DEFAULT NULL,
    `Net Debt to EBITDA` double DEFAULT NULL,
    `Cash Gen/Cash Reqd` double DEFAULT NULL,
    `AZS` double DEFAULT NULL,
    `Dvd Yld` double DEFAULT NULL,
    `Tobins Q` double DEFAULT NULL,
    `Board Size` double DEFAULT NULL,
    `Unit or 2 Tier Bd Sys` double DEFAULT NULL,
    `# Empl Reps on Bd` double DEFAULT NULL,
    `Clssfd Bd Sys` double DEFAULT NULL,
    `# Non Exec Dir on Bd` double DEFAULT NULL,
    `% NonExec Dir on Bd` double DEFAULT NULL,
    `% Indep Directors` double DEFAULT NULL,
    `Indep Directors` double DEFAULT NULL,
    `CEO Duality` double DEFAULT NULL,
    `Indep Chrprsn` double DEFAULT NULL,
    `Indep Lead Dir` double DEFAULT NULL,
    `Prsdg Dir` double DEFAULT NULL,
    `Frmr CEO or its Equiv on Bd` double DEFAULT NULL,
    `% Women on Bd` double DEFAULT NULL,
    `# Wmn on Bd` double DEFAULT NULL,
    `% Feml Execs` double DEFAULT NULL,
    `# Feml Execs` double DEFAULT NULL,
    `Feml CEO or Equiv` double DEFAULT NULL,
    `# Execs / Co Mgrs` double DEFAULT NULL,
    `Age Young Dir` double DEFAULT NULL,
    `BOD Age Rng` double DEFAULT NULL,
    `Age Old Dir` double DEFAULT NULL,
    `Bd Avg Age` double DEFAULT NULL,
    `Bd Age Limit` double DEFAULT NULL,
    `Board Duration` double DEFAULT NULL,
    `Exec Dir Bd Dur` double DEFAULT NULL,
    `Board Mtgs #` double DEFAULT NULL,
    `Board Mtg Att %` double DEFAULT NULL,
    `Indep Dir Bd Mtg Att %` double DEFAULT NULL,
    `Sz Aud Cmte` double DEFAULT NULL,
    `# Indep Dir on Aud Cmte` double DEFAULT NULL,
    `% Indep Dir on Aud Cmte` double DEFAULT NULL,
    `# Indep Dir on Comp Cmte` double DEFAULT NULL,
    `% Indep Dir on Comp Cmte` double DEFAULT NULL,
    `% Indep Dir on Nom Cmte` double DEFAULT NULL,
    `AZS.class` double DEFAULT NULL,
    `Tobins.Q.class` double DEFAULT NULL
  );
